#!/bin/bash

if [ "$#" -eq 2 ]; then
  app_type="Content-Type: application/json"
  load="{\"load\":${2}}"

  curl -H "${app_type}" -X POST -d "${load}" http://${1}:7777/set_load
fi

if [ "$#" -eq 1 ]; then
    curl http://${1}:7777/load
fi
